export const VERSES = [
  { text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", ref: "1 Corinthians 13:4" },
  { text: "As for me and my household, we will serve the Lord.", ref: "Joshua 24:15" },
  { text: "Children are a heritage from the Lord, offspring a reward from him.", ref: "Psalm 127:3" },
  { text: "Start children off on the way they should go, and even when they are old they will not turn from it.", ref: "Proverbs 22:6" },
  { text: "Husbands, love your wives, just as Christ loved the church and gave himself up for her.", ref: "Ephesians 5:25" },
  { text: "Two are better than one, because they have a good return for their labor.", ref: "Ecclesiastes 4:9" },
  { text: "A cord of three strands is not quickly broken.", ref: "Ecclesiastes 4:12" },
  { text: "Honor your father and your mother, so that you may live long in the land the Lord your God is giving you.", ref: "Exodus 20:12" },
  { text: "Bear one another's burdens, and so fulfill the law of Christ.", ref: "Galatians 6:2" },
  { text: "Be completely humble and gentle; be patient, bearing with one another in love.", ref: "Ephesians 4:2" },
  { text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", ref: "Jeremiah 29:11" },
  { text: "My grace is sufficient for you, for my power is made perfect in weakness.", ref: "2 Corinthians 12:9" },
  { text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", ref: "Romans 8:28" },
  { text: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.", ref: "Proverbs 3:5–6" },
  { text: "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus.", ref: "1 Thessalonians 5:16–18" },
  { text: "For where two or three gather in my name, there am I with them.", ref: "Matthew 18:20" },
  { text: "Above all, love each other deeply, because love covers over a multitude of sins.", ref: "1 Peter 4:8" },
  { text: "Let all that you do be done in love.", ref: "1 Corinthians 16:14" },
  { text: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.", ref: "Philippians 2:3" },
  { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
  { text: "She is clothed with strength and dignity; she can laugh at the days to come.", ref: "Proverbs 31:25" },
  { text: "He settles the childless woman in her home as a happy mother of children.", ref: "Psalm 113:9" },
  { text: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you.", ref: "Zephaniah 3:17" },
  { text: "Let perseverance finish its work so that you may be mature and complete, not lacking anything.", ref: "James 1:4" },
  { text: "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.", ref: "Colossians 3:12" },
  { text: "Forgive as the Lord forgave you.", ref: "Colossians 3:13" },
  { text: "And over all these virtues put on love, which binds them all together in perfect unity.", ref: "Colossians 3:14" },
  { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", ref: "Isaiah 40:31" },
  { text: "God sets the lonely in families.", ref: "Psalm 68:6" },
  { text: "Grandchildren are the crown of the aged, and the glory of children is their fathers.", ref: "Proverbs 17:6" },
  { text: "By wisdom a house is built, and through understanding it is established.", ref: "Proverbs 24:3" },
  { text: "Unless the Lord builds the house, the builders labor in vain.", ref: "Psalm 127:1" },
  { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
  { text: "Fathers, do not embitter your children, or they will become discouraged.", ref: "Colossians 3:21" },
  { text: "How good and pleasant it is when God's people live together in unity!", ref: "Psalm 133:1" },
  { text: "A generous person will prosper; whoever refreshes others will be refreshed.", ref: "Proverbs 11:25" },
];
